--CREATE DATABASE ERPSystem
-- Tabla de módulos
CREATE TABLE "modules" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(100) NOT NULL,
  "description" TEXT,
  "icon_url" TEXT,
  "created_by" INT,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de tablas (entidades relacionadas a un módulo)
CREATE TABLE "tables" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "module_id" INT NOT NULL,
  "name" VARCHAR(100) NOT NULL,
  "description" TEXT,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de columnas
CREATE TABLE "columns" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "table_id" INT NOT NULL,
  "name" VARCHAR(100) NOT NULL,
  "data_type" VARCHAR(50) NOT NULL,
  "is_required" BOOLEAN DEFAULT false,
  "is_foreign_key" BOOLEAN DEFAULT false,
  "foreign_table_id" INT,
  "foreign_column_name" VARCHAR(100),
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de registros (data en formato JSON)
CREATE TABLE "records" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "table_id" INT NOT NULL,
  "record_data" JSONB NOT NULL,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de usuarios
CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(100) NOT NULL,
  "email" VARCHAR(100) UNIQUE NOT NULL,
  "password_hash" TEXT NOT NULL,
  "is_active" BOOLEAN DEFAULT true,
  "is_blocked" BOOLEAN DEFAULT false,
  "last_login" TIMESTAMP,
  "avatar_url" TEXT
);

-- Historial de inicios de sesión
CREATE TABLE "user_login_history" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT NOT NULL,
  "login_time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "ip_address" TEXT,
  "user_agent" TEXT
);

-- Tabla de roles
CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(50) NOT NULL
);

-- Tabla intermedia entre usuarios y roles (muchos a muchos)
CREATE TABLE "user_roles" (
  "user_id" INT NOT NULL,
  "role_id" INT NOT NULL,
  PRIMARY KEY ("user_id", "role_id")
);

-- Tabla de permisos
CREATE TABLE "permissions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "table_id" INT NOT NULL,
  "role_id" INT NOT NULL,
  "can_create" BOOLEAN DEFAULT false,
  "can_read" BOOLEAN DEFAULT false,
  "can_update" BOOLEAN DEFAULT false,
  "can_delete" BOOLEAN DEFAULT false
);

-- Notificaciones
CREATE TABLE "notifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT NOT NULL,
  "title" VARCHAR(100) NOT NULL,
  "message" TEXT,
  "read" BOOLEAN DEFAULT false,
  "link_to_module" TEXT,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Comentarios
COMMENT ON COLUMN "modules"."icon_url" IS 'URL del ícono del módulo (Firebase Storage)';
COMMENT ON COLUMN "users"."is_active" IS 'Indica si el usuario está habilitado';
COMMENT ON COLUMN "users"."is_blocked" IS 'Indica si el usuario está bloqueado';
COMMENT ON COLUMN "users"."last_login" IS 'Fecha del último inicio de sesión';
COMMENT ON COLUMN "users"."avatar_url" IS 'URL del avatar o foto de perfil';
COMMENT ON COLUMN "user_login_history"."login_time" IS 'Fecha y hora del login';
COMMENT ON TABLE "user_roles" IS 'Tabla intermedia con PK compuesta usuario-rol';

-- Llaves foráneas
ALTER TABLE "modules" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "tables" ADD FOREIGN KEY ("module_id") REFERENCES "modules" ("id") ON DELETE CASCADE;
ALTER TABLE "columns" ADD FOREIGN KEY ("table_id") REFERENCES "tables" ("id") ON DELETE CASCADE;
ALTER TABLE "columns" ADD FOREIGN KEY ("foreign_table_id") REFERENCES "tables" ("id") ON DELETE SET NULL;
ALTER TABLE "records" ADD FOREIGN KEY ("table_id") REFERENCES "tables" ("id") ON DELETE CASCADE;
ALTER TABLE "user_login_history" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "user_roles" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE;
ALTER TABLE "permissions" ADD FOREIGN KEY ("table_id") REFERENCES "tables" ("id") ON DELETE CASCADE;
ALTER TABLE "permissions" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE;
ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
